"""
Pydantic schemas for API request/response validation.
"""
from pydantic import BaseModel, Field
from typing import Any
from datetime import datetime


# ── Inbound (from BOT LUA) ───────────────────────────────────────────────────

class QueryRequest(BaseModel):
    """Payload sent by BOT LUA when a student asks a question."""
    interaction_id: str = Field(
        ...,
        description="Unique conversation ID generated by BOT LUA.",
        examples=["lua_conv_abc123"],
    )
    materia_id: str = Field(
        ...,
        description="Subject/course ID. Must match a vectorized ChromaDB collection.",
        examples=["258_Criminologia_B"],
    )
    message: str = Field(
        ...,
        min_length=1,
        max_length=4096,
        description="Raw student message, may contain typos or emotional content.",
        examples=["no entiendo para que sirve la criminología??"],
    )


# ── Pre-processor output ─────────────────────────────────────────────────────

class PreprocessResult(BaseModel):
    """Structured output from the AI pre-processor (Worker 1)."""
    intent: str = Field(
        ...,
        description="Classified intent: academico | saludo | queja | fuera_de_tema",
    )
    sentiment: str = Field(
        ...,
        description="Emotional state: estresado | molesto | neutral | positivo",
    )
    clean_query: str = Field(
        ...,
        description="Polished query optimised for semantic vector search.",
    )
    confidence: float = Field(
        default=1.0,
        ge=0.0,
        le=1.0,
        description="Model confidence in the classification (0-1).",
    )


# ── RAG output ───────────────────────────────────────────────────────────────

class RetrievedChunk(BaseModel):
    """A single document chunk returned by ChromaDB."""
    content: str
    source: str                    # e.g. "contenido.txt" or "contenido.json"
    materia_id: str
    distance: float | None = None


class RAGResult(BaseModel):
    """Result from the vector search step."""
    chunks: list[RetrievedChunk]
    num_results: int


# ── Outbound (to BOT LUA) ────────────────────────────────────────────────────

class QueryResponse(BaseModel):
    """Full response returned to BOT LUA."""
    interaction_id: str
    materia_id: str
    response: str = Field(..., description="LLM-generated tutoring answer.")
    intent: str
    sentiment: str
    processing_time_ms: float
    status: str = "completed"


class ErrorResponse(BaseModel):
    detail: str
    interaction_id: str | None = None
    status: str = "error"


# ── Ingest ───────────────────────────────────────────────────────────────────

class IngestRequest(BaseModel):
    """Request to ingest/vectorize a materia's source files."""
    materia_id: str = Field(..., examples=["258_Criminologia_B"])
    force_reingest: bool = Field(
        default=False,
        description="If True, deletes existing collection and re-ingests.",
    )


class IngestResponse(BaseModel):
    materia_id: str
    status: str
    num_chunks: int = 0
    message: str


# ── Health ───────────────────────────────────────────────────────────────────

class HealthResponse(BaseModel):
    status: str
    version: str
    services: dict[str, Any]
    timestamp: datetime
